from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

from .rules import NativeRulesClient
from .teacher import FairyStockfishTeacher, TeacherEvaluation


class RulesSource(Protocol):
    def new_game(self) -> dict[str, Any]: ...
    def play_move(self, move: str) -> dict[str, Any]: ...


class MoveSource(Protocol):
    def evaluate_fen(self, fen: str, nodes: int) -> TeacherEvaluation: ...


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


@dataclass(frozen=True)
class GeneratedGame:
    positions: tuple[dict[str, Any], ...]
    result: str
    reason: str


FAIRY_MOVE = re.compile(r"^([a-i])(10|[1-9])([a-i])(10|[1-9])$")


def fairy_move_to_ucci(move: str) -> str:
    """Convert Fairy-Stockfish's files/1..10 ranks to UCCI files/0..9 ranks."""
    match = FAIRY_MOVE.fullmatch(move)
    if match is None:
        raise ValueError(f"invalid Fairy-Stockfish Xiangqi move {move}")
    return (
        match.group(1)
        + str(int(match.group(2)) - 1)
        + match.group(3)
        + str(int(match.group(4)) - 1)
    )


def _outcome(result: str, fen: str) -> float:
    if result == "draw":
        return 0.0
    red = result == "red_win"
    red_to_move = fen.split()[1] == "w"
    return 1.0 if red == red_to_move else -1.0


def play_game(
    rules: RulesSource,
    teacher: MoveSource,
    rng: random.Random,
    *,
    nodes: int,
    max_plies: int,
    random_plies: int,
) -> GeneratedGame:
    if nodes <= 0 or max_plies <= 0 or random_plies < 0:
        raise ValueError("nodes/max_plies must be positive and random_plies non-negative")
    snapshot = rules.new_game()
    positions: list[dict[str, Any]] = []
    for ply in range(max_plies):
        result = snapshot["result"]
        if result["kind"] != "ongoing":
            break
        fen = snapshot["fen"]
        positions.append({"fen": fen, "ply": ply})
        legal = snapshot["legalMoves"]
        if not legal:
            raise ValueError("ongoing rules snapshot has no legal moves")
        if ply < random_plies:
            move = rng.choice(legal)
        else:
            move = fairy_move_to_ucci(teacher.evaluate_fen(fen, nodes).bestmove)
            if move not in legal:
                raise ValueError(f"teacher returned illegal move {move}")
        snapshot = rules.play_move(move)
    result = snapshot["result"]
    kind = result["kind"] if result["kind"] != "ongoing" else "draw"
    reason = result["reason"] if result["kind"] != "ongoing" else "max_plies"
    return GeneratedGame(
        tuple({**position, "outcome": _outcome(kind, position["fen"])} for position in positions),
        kind,
        reason,
    )


class SelfplaySourceWriter:
    def __init__(self, directory: Path, config: dict[str, Any]):
        directory.mkdir(parents=True, exist_ok=True)
        self.directory = directory
        self.manifest_path = directory / "manifest.json"
        if self.manifest_path.exists():
            self.manifest = json.loads(self.manifest_path.read_text(encoding="utf-8"))
            if self.manifest.get("config") != config:
                raise ValueError("self-play configuration does not match the existing manifest")
        else:
            self.manifest = {
                "schemaVersion": 1,
                "license": "ODbL-1.0",
                "attribution": "Generated by Anchen0823/xiangqi-rl",
                "config": config,
                "totalRecords": 0,
                "games": [],
            }
            self._write_manifest()

    def _write_manifest(self) -> None:
        temporary = self.manifest_path.with_suffix(".json.tmp")
        temporary.write_text(json.dumps(self.manifest, indent=2) + "\n", encoding="utf-8")
        os.replace(temporary, self.manifest_path)

    def add(self, game: GeneratedGame) -> None:
        index = len(self.manifest["games"])
        final = self.directory / f"game-{index:06d}.jsonl"
        partial = final.with_suffix(".jsonl.partial")
        with partial.open("wt", encoding="utf-8", newline="\n") as stream:
            for position in game.positions:
                stream.write(json.dumps(position, separators=(",", ":")) + "\n")
        os.replace(partial, final)
        self.manifest["games"].append({
            "file": final.name,
            "records": len(game.positions),
            "result": game.result,
            "reason": game.reason,
            "sha256": sha256(final),
        })
        self.manifest["totalRecords"] += len(game.positions)
        self._write_manifest()


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate ODbL self-play source positions")
    parser.add_argument("--rules-engine", type=Path, required=True)
    parser.add_argument("--teacher-engine", type=Path, required=True)
    parser.add_argument("--teacher-manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--games", type=int, required=True)
    parser.add_argument("--nodes", type=int, default=2_000)
    parser.add_argument("--max-plies", type=int, default=240)
    parser.add_argument("--random-plies", type=int, default=4)
    parser.add_argument("--seed", type=int, default=823)
    args = parser.parse_args()
    teacher_manifest = json.loads(args.teacher_manifest.read_text(encoding="utf-8"))
    teacher_hash = sha256(args.teacher_engine)
    if teacher_manifest.get("networkLicense") != "CC0-1.0":
        raise ValueError("self-play teacher network must be CC0-1.0")
    if teacher_hash != teacher_manifest.get("assetSha256"):
        raise ValueError("teacher executable SHA-256 does not match its manifest")
    config = {
        "rulesSha256": sha256(args.rules_engine),
        "teacherSha256": teacher_hash,
        "teacherNetwork": teacher_manifest["network"],
        "nodes": args.nodes,
        "maxPlies": args.max_plies,
        "randomPlies": args.random_plies,
        "seed": args.seed,
    }
    writer = SelfplaySourceWriter(args.output, config)
    completed = len(writer.manifest["games"])
    if args.games < completed:
        raise ValueError("requested game count is below the completed manifest count")
    with NativeRulesClient(args.rules_engine) as rules:
        with FairyStockfishTeacher(args.teacher_engine) as teacher:
            for game_index in range(completed, args.games):
                game = play_game(
                    rules,
                    teacher,
                    random.Random(args.seed + game_index * 1_000_003),
                    nodes=args.nodes,
                    max_plies=args.max_plies,
                    random_plies=args.random_plies,
                )
                writer.add(game)
                print(json.dumps({
                    "game": game_index,
                    "records": len(game.positions),
                    "result": game.result,
                    "reason": game.reason,
                }), flush=True)


if __name__ == "__main__":
    main()
