import { describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { actionKey, type Piece, type Scenario } from '../variants/types';
import { createRules, cycleResult, determinize, legalActions, makeScenario, mirrorScenario, newGame, observe, play, rulesHash, square, chaseTargets } from '../variants/rules';
import { canonical, hash, Random } from '../variants/random';
import { encode } from '../variants/features';
import { search } from '../variants/search';
import { loadVariant, saveVariant } from '../variants/storage';

function custom(items:[string,string,string][]):Scenario{
  const s=makeScenario('custom',1,'standard');s.pieces=items.map(([kind,color,pos],id)=>({id,kind,color:color as Piece['color'],square:square(pos),role:kind,hidden:false}));return s;
}
const has=(s:ReturnType<typeof newGame>,from:string,to:string)=>legalActions(s).some(a=>a.type==='move'&&a.from===square(from,s.scenario.rules.width)&&a.to===square(to,s.scenario.rules.width));
describe('variant rules',()=>{
  it('SHA256 and canonical rule hashes are portable',()=>{const v={z:4,a:['中',1]};expect(hash(v)).toBe(createHash('sha256').update(canonical(v)).digest('hex'));expect(rulesHash(createRules('jieqi'))).toBe(rulesHash(createRules('jieqi')));});
  it('standard opening has exactly 44 legal moves',()=>expect(legalActions(newGame(makeScenario('custom',1,'standard')))).toHaveLength(44));
  it('all presets and their color reversals are playable',()=>{for(const id of ['queen-left-2','queen-right-2','queen-left-3','queen-right-3','ending-2','ending-3']){const s=makeScenario('custom',1,id);expect(legalActions(newGame(s)).length).toBeGreaterThan(0);expect(legalActions(newGame(mirrorScenario(s))).length).toBeGreaterThan(0);}});
  it('queen cannot jump blockers or expose its king',()=>{const s=newGame(custom([['k','red','d0'],['k','black','f9'],['q','red','b2'],['p','red','d4']]));expect(has(s,'b2','c3')).toBe(true);expect(has(s,'b2','e5')).toBe(false);expect(has(s,'b2','b7')).toBe(true);});
  it('horse legs and cannon screens',()=>{const s=newGame(custom([['k','red','d0'],['k','black','f9'],['n','red','b0'],['p','red','b1'],['c','red','e2'],['p','red','e4'],['r','black','e7']]));expect(has(s,'b0','c2')).toBe(false);expect(has(s,'e2','e7')).toBe(true);});
  it('rejects exposed generals and duplicate squares',()=>{expect(()=>newGame(custom([['k','red','e0'],['k','black','e9']]))).toThrow();const s=makeScenario('custom');s.pieces[0].square=s.pieces[1].square;expect(()=>newGame(s)).toThrow();});
  it('king cannot be captured, and a pinned blocker cannot leave',()=>{const s=newGame(custom([['k','red','e0'],['k','black','f9'],['q','red','e2'],['r','black','e7']]));expect(has(s,'e2','d2')).toBe(false);expect(has(s,'e2','e7')).toBe(true);});
  it('custom vectors support independent move and capture rules',()=>{const s=custom([['k','red','d0'],['k','black','f9'],['x','red','c3'],['p','black','f3']]);s.rules.pieces.push({id:'x',label:'跃',moves:[{directions:[[2,0]],max:1,jump:true}],captures:[{directions:[[3,0]],max:1,jump:true}]});const g=newGame(s);expect(has(g,'c3','e3')).toBe(true);expect(has(g,'c3','f3')).toBe(true);});
  it('jieqi first step uses role and reveals, then advisors leave palace',()=>{const s=custom([['k','red','d0'],['k','black','f9'],['a','red','a0']]);s.rules=createRules('jieqi');s.pieces[2]={...s.pieces[2],hidden:true,role:'r'};let g=newGame(s);expect(has(g,'a0','a4')).toBe(true);g=play(g,{type:'move',from:0,to:square('a4')});expect(g.pieces.find(p=>p.id===2)?.hidden).toBe(false);g.turn=0;expect(has(g,'a4','b5')).toBe(true);expect(has(g,'a4','a5')).toBe(false);});
  it('jieqi captured identity is private and unknown graves remain in samples',()=>{const s=custom([['k','red','d0'],['k','black','f9'],['r','red','a0'],['n','black','a3'],['c','black','i6']]);s.rules=createRules('jieqi');s.pieces[3].hidden=true;s.pieces[3].role='p';s.pieces[4].hidden=true;s.pieces[4].role='p';const g=play(newGame(s),{type:'move',from:0,to:square('a3')});expect(observe(g,0).captures[0].kind).toBe('n');const o=observe(g,1);expect(o.captures[0].kind).toBe(null);const possible=new Set(Array.from({length:30},(_,i)=>determinize(o,new Random(i)).captures[0].kind));expect(possible).toEqual(new Set(['n','c']));});
  it('banqi first flip assigns color to seat and consumes a turn',()=>{const g=newGame(makeScenario('banqi',4));expect(legalActions(g).every(a=>a.type==='flip')).toBe(true);const p=g.pieces[0],n=play(g,{type:'flip',square:p.square});expect(n.seats[0]).toBe(p.color);expect(n.turn).toBe(1);});
  it('banqi cannon can eat a hidden friendly piece, publicly',()=>{const s=makeScenario('banqi',1);s.seats=['red','black'];s.pieces=[{id:0,kind:'c',role:'?',color:'red',square:0,hidden:false},{id:1,kind:'p',role:'?',color:'black',square:4,hidden:true},{id:2,kind:'r',role:'?',color:'red',square:8,hidden:true}];const g=newGame(s);expect(has(g,'a0','a2')).toBe(true);const n=play(g,{type:'move',from:0,to:8});expect(n.pieces.find(p=>p.id===0)?.square).toBe(8);expect(n.pieces.some(p=>p.id===2)).toBe(false);expect(observe(n,1).captures[0].kind).toBe('r');});
  it('banqi pawn/king exception and cannon cannot eat adjacent',()=>{const s=makeScenario('banqi');s.seats=['red','black'];s.pieces=[{id:0,kind:'p',role:'?',color:'red',square:0,hidden:false},{id:1,kind:'k',role:'?',color:'black',square:1,hidden:false},{id:2,kind:'c',role:'?',color:'red',square:5,hidden:false}];let g=newGame(s);expect(legalActions(g).map(actionKey)).toContain('m0:1');expect(legalActions(g).map(actionKey)).not.toContain('m5:1');g.turn=1;expect(legalActions(g).map(actionKey)).not.toContain('m1:0');});
  it('cycle responsibility covers check, chase, mixed, mutual and changing targets',()=>{
    const row=(seat:0|1,check:boolean,chased:number[])=>({seat,check,chased});
    expect(cycleResult([row(0,true,[]),row(1,false,[2]),row(0,true,[]),row(1,false,[2])])).toMatchObject({winner:1,reason:'perpetual_check'});
    expect(cycleResult([row(0,true,[]),row(1,false,[]),row(0,false,[2]),row(1,false,[])])).toMatchObject({winner:1,reason:'perpetual_chase'});
    expect(cycleResult([row(0,false,[2]),row(1,false,[4]),row(0,false,[2]),row(1,false,[4])]).kind).toBe('draw');
    expect(cycleResult([row(0,false,[2]),row(1,false,[]),row(0,false,[3]),row(1,false,[])]).kind).toBe('draw');
  });
  it('threefold reversible sequence and quiet counter adjudicate',()=>{let g=newGame(custom([['k','red','d0'],['k','black','f9'],['n','red','a0'],['n','black','i9']]));const moves=[['a0','b2'],['i9','h7'],['b2','a0'],['h7','i9']];for(const [a,b]of [...moves,...moves])g=play(g,{type:'move',from:square(a),to:square(b)});expect(g.result).toMatchObject({kind:'draw',reason:'mutual_repetition'});let h=newGame(custom([['k','red','d0'],['k','black','f9'],['n','red','a0']]));h.quiet=119;h=play(h,{type:'move',from:0,to:square('b2')});expect(h.result.reason).toBe('natural_limit');});
  it('chase excludes unchanged threats and legal recaptures',()=>{const s=custom([['k','red','d0'],['k','black','f9'],['r','red','a0'],['n','black','b6']]);const after=s.pieces.map(p=>p.id===2?{...p,square:square('b0')}:p);expect(chaseTargets(s.pieces,after,2,'red',s.rules)).toContain(3);expect(chaseTargets(after,after,2,'red',s.rules)).toEqual([]);const protectedBefore=[...s.pieces,{id:4,kind:'r',role:'r',color:'black' as const,square:square('i6'),hidden:false}];const protectedAfter=protectedBefore.map(p=>p.id===2?{...p,square:square('b0')}:p);expect(chaseTargets(protectedBefore,protectedAfter,2,'red',s.rules)).toEqual([]);});
  it('saved games replay identically and reject tampering',()=>{const g=newGame(makeScenario('jieqi',8));const n=play(g,legalActions(g)[0]);expect(loadVariant(saveVariant(n))).toEqual(n);const data=saveVariant(n);data.rulesHash='bad';expect(()=>loadVariant(data)).toThrow();});
  it('no peeking: indistinguishable observations, features and AI actions',async()=>{for(const mode of ['jieqi','banqi'] as const){const g=newGame(makeScenario(mode,18)),h=structuredClone(g);const hidden=h.pieces.filter(p=>p.hidden&&p.color==='red');[hidden[0].kind,hidden[1].kind]=[hidden[1].kind,hidden[0].kind];const a=observe(g,0),b=observe(h,0);expect(b).toEqual(a);expect(encode(b)).toEqual(encode(a));const budget={nodes:24,rollout:2,seed:42};const x=await search(a,budget),y=await search(b,budget);expect(y.action).toEqual(x.action);expect(y.policy).toEqual(x.policy);expect(x.nodes).toBeLessThanOrEqual(24);}});
  it('mate takes priority over the quiet limit in the agreed ending',()=>{const g=newGame(makeScenario('custom',1,'ending-2'));g.quiet=119;expect(play(g,{type:'move',from:square('e2'),to:square('e8')}).result).toEqual({kind:'win',winner:0,reason:'checkmate'});});
  it('revealed jieqi elephants cross the river but still have blocked eyes',()=>{const s=custom([['k','red','d0'],['k','black','f9'],['b','red','c4'],['p','red','b5']]);s.rules=createRules('jieqi');const g=newGame(s);expect(has(g,'c4','e6')).toBe(true);expect(has(g,'c4','a6')).toBe(false);});
  it('custom cannon requires exactly two screens when specified',()=>{const s=custom([['k','red','d0'],['k','black','f9'],['x','red','a0'],['p','red','a1'],['p','red','a2'],['n','black','a6']]);s.rules.pieces.push({id:'x',label:'双',moves:[],captures:[{directions:[[0,1]],max:0,screens:2}]});expect(has(newGame(s),'a0','a6')).toBe(true);s.pieces=s.pieces.filter(p=>p.square!==square('a2'));expect(has(newGame(s),'a0','a6')).toBe(false);});
  it('chase exemptions, reciprocal exchange and discovered attacks use public roles',()=>{const s=custom([['k','red','d0'],['k','black','f9'],['r','red','a0'],['r','black','b6']]);const after=s.pieces.map(p=>p.id===2?{...p,square:square('b0')}:p);expect(chaseTargets(s.pieces,after,2,'red',s.rules)).toEqual([]);s.pieces[3].kind=s.pieces[3].role='p';const pawnAfter=s.pieces.map(p=>p.id===2?{...p,square:square('b0')}:p);expect(chaseTargets(s.pieces,pawnAfter,2,'red',s.rules)).toEqual([]);
    const d=custom([['k','red','d0'],['k','black','f9'],['r','red','a0'],['p','red','a2'],['n','black','a6']]);const discovered=d.pieces.map(p=>p.id===3?{...p,square:square('b2')}:p);expect(chaseTargets(d.pieces,discovered,3,'red',d.rules)).toContain(4);
  });
  it('unknown captured identities do not leak into features, history or search',async()=>{const s=custom([['k','red','d0'],['k','black','f9'],['r','red','a0'],['n','black','a3'],['c','black','i6']]);s.rules=createRules('jieqi');for(const p of s.pieces.slice(3)){p.hidden=true;p.role='p';}const g=play(newGame(s),{type:'move',from:0,to:square('a3')}),h=structuredClone(g);h.captures[0].kind='c';h.pieces.find(p=>p.id===4)!.kind='n';const a=observe(g,1),b=observe(h,1);expect(a).toEqual(b);expect(encode(a)).toEqual(encode(b));const budget={nodes:32,seed:7,rollout:4};expect((await search(a,budget)).policy).toEqual((await search(b,budget)).policy);});
});
